const quizData = [
  {
    question: 'What country has the highest life expectancy?',
    first: 'Hong Kong',
    second: 'America',
    third: 'Japan',
    forth: 'Italy',
    fifth: 'Brazil',
    correct: 'first',
  },
  {
    question: 'What language has the more native speakers?',
    first: 'Japanese',
    second: 'Spanish',
    third: 'French',
    forth: 'Chinese',
    fifth: 'English',
    correct: 'second',
  },
  {
    question: 'How many minutes are in a full week?',
    first: '10000',
    second: '10080',
    third: '10800',
    forth: '9800',
    fifth: '8880',
    correct: 'second',
  },
  {
    question: 'What year was the United Nations established?',
    first: '1900',
    second: '1850',
    third: '1923',
    forth: '550',
    fifth: '1945',
    correct: 'fifth',
  },
  {
    question: 'How many colors are there on the logo of Microsoft Corp.?',
    first: '2',
    second: '3',
    third: '4',
    forth: '5',
    fifth: 'none of above',
    correct: 'third',
  },
];
